org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.configuration-cache=true

modId=jiv
modName=Just Items Viewer
modGroup=eakerzt.jiv
modAuthor=eakerzt
modVersion=0.0.1-alpha-1
modDescription=An item and recipe viewer for NeoForge, derived from Just Enough Items.
modJavaVersion=25

minecraftVersion=26.1.2
minecraftVersionRange=[26.1.2]
neoforgeVersion=26.1.2.99
neoforgeVersionRange=[26.1.2.99,26.2)
neoforgeLoaderVersionRange=[4,)

jUnitVersion=6.1.3
